before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: ./cmd/bloopsbot-srv
    id: srv
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: bloopsbot-srv
  - main: ./cmd/bloopsbot-cli
    id: cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: bloopsbot-cli
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
